baseUrl = "https://blog.bacongobbler.com"
CanonifyUrls = true
languageCode = "en-us"
title = "Matt Fisher's Blog"
pygmentsCodeFences = true
pygmentsStyle = "native"

[Author]
    Name = "Matthew Fisher"
    Position = "Software Engineer"
    Email = "matt.fisher@fishworks.io"
    Github = "bacongobbler"
    Twitter = "bacongobbler"
