baseUrl = "/"
CanonifyUrls = true
languageCode = "en-us"
title = "Matt Fisher's Blog"
pygmentsCodeFences = true
pygmentsStyle = "native"
theme = "arabica"

[Author]
    Name = "Matthew Fisher"
    Position = "Software Engineer"
    Email = "matt.fisher@fishworks.io"
    Github = "bacongobbler"
    Twitter = "bacongobbler"

[params]
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
