version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - run:
          name: build
          command: .circleci/build.sh
      - deploy:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
